SELECT SCHEMA_NAME  FROM INFORMATION_SCHEMA.SCHEMATA
WHERE SCHEMA_NAME = 'testchorddb';
CREATE DATABASE IF NOT EXISTS `testchorddb`; /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;